FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Directory.Build.props Directory.Packages.props global.json ./
COPY shared/ shared/
COPY services/orders-service/ services/orders-service/
WORKDIR /src/services/orders-service
RUN dotnet restore Orders.sln
RUN dotnet publish src/Orders.Worker/Orders.Worker.csproj -c Release -o /app /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Orders.Worker.dll"]
