<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\..\shared\contracts\Notifications.Contracts\Notifications.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\shared\contracts\Orders.Contracts\Orders.Contracts.csproj" />
    <ProjectReference Include="..\Notifications.Domain\Notifications.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
